name: Docker Image Packer

on:
  workflow_dispatch: # 允许我们手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Docker Image
        run: |
          # 1. 强行拉取官方镜像（GitHub 速度极快）
          docker pull akiralereal/iptv:v3.6.0
          
          # 2. 将镜像保存为 tar 包
          docker save -o iptv.tar akiralereal/iptv:v3.6.0
          
      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iptv-image-tar
          path: iptv.tar
