name: Docker Image Packer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Docker Image
        run: |
          # 使用绝对不会错的万能最新版标签 latest
          docker pull akiralereal/iptv:latest
          docker save -o iptv.tar akiralereal/iptv:latest
          
      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iptv-image-tar
          path: iptv.tar
