name: Docker Image Packer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Docker Image
        run: |
          # 改为官方真实存在的最新版本 v3.5.3
          docker pull akiralereal/iptv:v3.5.3
          docker save -o iptv.tar akiralereal/iptv:v3.5.3
          
      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iptv-image-tar
          path: iptv.tar
