name: Docker 镜像全自动实时构建器

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. 克隆作者最新的全部源代码
        run: |
          git clone https://github.com/akiralereal/iptv.git .

      - name: 2. 自动化提取并对齐作者的最新版本号
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "DETECTED_VERSION=v$VERSION" >> $GITHUB_ENV
          echo "成功精准捕获到作者最新版本号: v$VERSION"

      - name: 3. 云端现场编译最新版镜像
        run: |
          docker build -t akiralereal/iptv:${{ env.DETECTED_VERSION }} .
          docker tag akiralereal/iptv:${{ env.DETECTED_VERSION }} akiralereal/iptv:latest

      - name: 4. 将新鲜出炉的真正新镜像打包备用
        run: |
          docker save -o iptv.tar akiralereal/iptv:${{ env.DETECTED_VERSION }}

      - name: 5. 上传大礼包到 GitHub 构件下载区
        uses: actions/upload-artifact@v4
        with:
          name: iptv-${{ env.DETECTED_VERSION }}-real
          path: iptv.tar
